version: '3.8'

services:
  mop-webapp-staging:
    image: tracynguyen203/mop-webapp:staging
    container_name: mop-webapp-staging
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - PORT=3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3