version: '3.8'

services:
  mop-webapp-prod:
    image: tracynguyen203/mop-webapp:latest
    container_name: mop-webapp-prod
    restart: always
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3