sonar.projectKey=MOP-Code
sonar.projectName=MOP-Code
sonar.projectVersion=1.0

sonar.sources=next_webapp
sonar.javascript.lcov.reportPaths=next_webapp/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/.next/**,**/out/**,**/coverage/**,**/*.config.js,**/my-app/**

sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8